[package]
name = "poem-ext"
version = "0.1.0"
description = "Extension crate for poem/poem-openapi"
license = "MIT"
documentation = "https://docs.rs/poem-ext/"
edition = "2021"

[features]
default = ["sea-orm"]
sea-orm = ["dep:sea-orm"]

[dependencies]
poem = { version = "1.3.55", default-features = false }
poem-openapi = { version = "2.0.26", default-features = false }
sea-orm = { version = "0.11.1", default-features = false, optional = true }

[dev-dependencies]
tokio = { version = "1.26.0", default-features = false, features = ["rt-multi-thread"] }
